[package]
name = "sodoken"
version = "0.0.1-alpha.8"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "libsodium wrapper providing tokio safe memory secure api access."
keywords = [ "holochain", "holo", "nacl", "libsodium", "cryptography" ]
categories = [ "cryptography" ]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/sodoken"
repository = "https://github.com/holochain/sodoken"

[dependencies]
libc = "0.2.98"
libsodium-sys = "0.2.7"
num_cpus = "1.13.0"
once_cell = "1.8.0"
parking_lot = "0.11.1"
thiserror = "1.0.26"
tokio = { version = "1.8.1", features = ["sync", "rt"] }

[dev-dependencies]
criterion = "0.3.4"
tokio = { version = "1.8.1", features = ["full"] }

[[bench]]
name = "blake2b"
harness = false

[[bench]]
name = "random"
harness = false

[[bench]]
name = "sign"
harness = false
