[package]
name = "sodoken"
version = "0.0.1-alpha.4"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"
description = "libsodium wrapper providing tokio safe memory secure api access."
keywords = [ "holochain", "holo", "nacl", "libsodium", "cryptography" ]
categories = [ "cryptography" ]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/sodoken"
repository = "https://github.com/holochain/sodoken"

[dependencies]
libc = "0.2"
libsodium-sys = "0.2.6"
once_cell = "1.7"
parking_lot = "0.11"
thiserror = "1"
tokio = { version = "1.6", features = ["sync", "rt"] }

[dev-dependencies]
tokio = { version = "1.6", features = ["full"] }
